
  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8502
  Network URL: http://172.30.0.171:8502

  For better performance, install the Watchdog module:

  $ xcode-select --install
  $ pip install watchdog
            

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8503
  Network URL: http://172.30.0.171:8503

  For better performance, install the Watchdog module:

  $ xcode-select --install
  $ pip install watchdog
            
2025-06-30 14:08:12.914 Uncaught app execution
Traceback (most recent call last):
  File "/Users/peter/miniforge3/envs/env-streamlit-addaxai/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/Users/peter/miniforge3/envs/env-streamlit-addaxai/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 645, in code_to_exec
    exec(code, module.__dict__)
  File "/Applications/AddaxAI_files/AddaxAI/streamlit-AddaxAI/main.py", line 274, in <module>
    pg.run()
  File "/Users/peter/miniforge3/envs/env-streamlit-addaxai/lib/python3.11/site-packages/streamlit/navigation/page.py", line 297, in run
    exec(code, module.__dict__)
  File "/Applications/AddaxAI_files/AddaxAI/streamlit-AddaxAI/pages/analyse_advanced.py", line 211, in <module>
    add_deployment(selected_min_datetime = selected_min_datetime)
  File "/Applications/AddaxAI_files/AddaxAI/streamlit-AddaxAI/ads_utils/common.py", line 602, in add_deployment
    location = project["locations"][selected_locationID]
               ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: None
2025-06-30 14:09:50.601 Uncaught app execution
Traceback (most recent call last):
  File "/Users/peter/miniforge3/envs/env-streamlit-addaxai/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/Users/peter/miniforge3/envs/env-streamlit-addaxai/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 645, in code_to_exec
    exec(code, module.__dict__)
  File "/Applications/AddaxAI_files/AddaxAI/streamlit-AddaxAI/main.py", line 274, in <module>
    pg.run()
  File "/Users/peter/miniforge3/envs/env-streamlit-addaxai/lib/python3.11/site-packages/streamlit/navigation/page.py", line 297, in run
    exec(code, module.__dict__)
  File "/Applications/AddaxAI_files/AddaxAI/streamlit-AddaxAI/pages/analyse_advanced.py", line 211, in <module>
    add_deployment(selected_min_datetime = selected_min_datetime)
  File "/Applications/AddaxAI_files/AddaxAI/streamlit-AddaxAI/ads_utils/common.py", line 602, in add_deployment
    location = project["locations"][selected_locationID]
               ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: None
2025-06-30 14:10:15.499 Uncaught app execution
Traceback (most recent call last):
  File "/Users/peter/miniforge3/envs/env-streamlit-addaxai/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/Users/peter/miniforge3/envs/env-streamlit-addaxai/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 645, in code_to_exec
    exec(code, module.__dict__)
  File "/Applications/AddaxAI_files/AddaxAI/streamlit-AddaxAI/main.py", line 274, in <module>
    pg.run()
  File "/Users/peter/miniforge3/envs/env-streamlit-addaxai/lib/python3.11/site-packages/streamlit/navigation/page.py", line 297, in run
    exec(code, module.__dict__)
  File "/Applications/AddaxAI_files/AddaxAI/streamlit-AddaxAI/pages/analyse_advanced.py", line 217, in <module>
    add_deployment(selected_min_datetime = selected_min_datetime)
  File "/Applications/AddaxAI_files/AddaxAI/streamlit-AddaxAI/ads_utils/common.py", line 627, in add_deployment
    "deploymentStart": datetime.isoformat(),
                       ^^^^^^^^^^^^^^^^^^^^
TypeError: unbound method datetime.isoformat() needs an argument
2025-06-30 14:10:59.154 Uncaught app execution
Traceback (most recent call last):
  File "/Users/peter/miniforge3/envs/env-streamlit-addaxai/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/Users/peter/miniforge3/envs/env-streamlit-addaxai/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 645, in code_to_exec
    exec(code, module.__dict__)
  File "/Applications/AddaxAI_files/AddaxAI/streamlit-AddaxAI/main.py", line 274, in <module>
    pg.run()
  File "/Users/peter/miniforge3/envs/env-streamlit-addaxai/lib/python3.11/site-packages/streamlit/navigation/page.py", line 297, in run
    exec(code, module.__dict__)
  File "/Applications/AddaxAI_files/AddaxAI/streamlit-AddaxAI/pages/analyse_advanced.py", line 217, in <module>
    add_deployment(selected_min_datetime = selected_min_datetime)
  File "/Applications/AddaxAI_files/AddaxAI/streamlit-AddaxAI/ads_utils/common.py", line 627, in add_deployment
    "deploymentStart": datetime.isoformat(),
                       ^^^^^^^^^^^^^^^^^^^^
TypeError: unbound method datetime.isoformat() needs an argument
2025-06-30 14:15:10.106 Uncaught app execution
Traceback (most recent call last):
  File "/Users/peter/miniforge3/envs/env-streamlit-addaxai/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/Users/peter/miniforge3/envs/env-streamlit-addaxai/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 645, in code_to_exec
    exec(code, module.__dict__)
  File "/Applications/AddaxAI_files/AddaxAI/streamlit-AddaxAI/main.py", line 274, in <module>
    pg.run()
  File "/Users/peter/miniforge3/envs/env-streamlit-addaxai/lib/python3.11/site-packages/streamlit/navigation/page.py", line 297, in run
    exec(code, module.__dict__)
  File "/Applications/AddaxAI_files/AddaxAI/streamlit-AddaxAI/pages/analyse_advanced.py", line 219, in <module>
    add_deployment(selected_min_datetime = selected_min_datetime)
  File "/Applications/AddaxAI_files/AddaxAI/streamlit-AddaxAI/ads_utils/common.py", line 616, in add_deployment
    time.sleep(1)
    ^^^^^^^^^^
AttributeError: type object 'datetime.time' has no attribute 'sleep'
